import test from 'node:test';
import assert from 'node:assert/strict';
import {calculate} from '../dyson/model.mjs';
import {BenchNode} from '../dyson/controller.mjs';
test('power budget preserves gross inverse-square scaling and zero unvalidated delivery',()=>{const r=calculate();assert.ok(Math.abs(r.net-262.3776)<1e-8);assert.equal(r.delivered,0);assert.equal(r.capitalPerKwh,null);assert.equal(calculate({au:2}).gross,r.gross/4);assert.equal(calculate({failure:1}).fleet,0);assert.equal(calculate({area:0}).net,0);assert.throws(()=>calculate({delivery:1.1}));assert.throws(()=>calculate({au:0}));});
test('delivery matches independently specified investment base with annual failure and degradation',()=>{const r=calculate({count:1,delivery:0.25});assert.equal(r.delivered,r.fleet/4);assert.ok(Math.abs(r.energy-1802.1471639596175)<1e-8);assert.ok(Math.abs(r.capitalPerKwh-97.66128067660063)<1e-8);});
test('node rejects expired and replayed commands; coordinator loss preserves local tracking',()=>{const n=new BenchNode('A');assert.equal(n.command({type:'DEPLOY',sequence:1,expiresAt:0},1),false);assert.equal(n.mode,'STOWED');assert.equal(n.command({type:'DEPLOY',sequence:2,expiresAt:5},1),true);assert.equal(n.command({type:'RESET',sequence:2,expiresAt:5},2),false);const r=n.step({sunAngle:30},3,32);assert.equal(r.angle,30);assert.equal(r.mode,'TRACK');assert.equal(r.autonomous,true);assert.ok(r.netW>0);});
test('one failed node cannot disable neighbors and safe state requires explicit reset',()=>{const nodes=['A','B','C'].map(id=>new BenchNode(id));nodes.forEach(n=>n.command({type:'DEPLOY',sequence:1,expiresAt:5},0));nodes.forEach(n=>n.step({},1,1));const r=nodes.map((n,i)=>n.step({connected:i!==1},1,2));assert.deepEqual(r.map(n=>n.mode),['TRACK','SAFE','TRACK']);assert.equal(r[1].loadW,0);assert.equal(nodes[1].step({},1,3).mode,'SAFE');nodes[1].command({type:'RESET',sequence:2,expiresAt:5},3);assert.equal(nodes[1].mode,'STOWED');});
test('temperature and invalid sensor protect load even with fresh commands',()=>{const n=new BenchNode('A');n.command({type:'DEPLOY',sequence:1,expiresAt:10},0);assert.equal(n.step({temperature:65},1,1).loadW,0);assert.equal(n.fault,'overtemperature');n.command({type:'RESET',sequence:2,expiresAt:10},2);assert.equal(n.step({sunAngle:NaN},1,3).mode,'SAFE');});
