import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {BASE,calculate} from './model.mjs';
import './bench-ui.js';
const $ = id=>document.getElementById(id);
let paused=false, mode='single', scenario={...BASE};
const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));$('canvas').append(renderer.domElement);
const scene=new THREE.Scene();const camera=new THREE.PerspectiveCamera(38,1,0.01,100);camera.position.set(1.3,1.6,2.2);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=0.8;controls.maxDistance=12;controls.autoRotate=true;controls.autoRotateSpeed=0.7;
scene.add(new THREE.HemisphereLight(0xd7ebff,0x283244,3));const light=new THREE.DirectionalLight(0xffe3ad,4);light.position.set(2,4,3);scene.add(light);
const drone=new THREE.Group();const material=new THREE.MeshStandardMaterial({color:0x234b8d,metalness:0.55,roughness:0.32});const metal=new THREE.MeshStandardMaterial({color:0xb9c3ca,metalness:0.7,roughness:0.4});
function box(w,h,d,mat,x,y,z,parent=drone){const mesh=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);mesh.position.set(x,y,z);parent.add(mesh);return mesh;}
for(const x of [-0.25,0.25])for(const z of [-0.25,0.25]){box(0.498,0.012,0.498,metal,x,0,z);box(0.49,0.002,0.49,material,x,0.007,z);for(let k=1;k<8;k++){box(0.001,0.001,0.49,metal,x-0.245+k*0.06125,0.009,z);box(0.49,0.001,0.001,metal,x,0.009,z-0.245+k*0.06125);}}
box(0.2,0.2,0.2,metal,0,-0.105,0);box(0.14,0.002,0.14,new THREE.MeshStandardMaterial({color:0x11151a}),0,-0.206,0);
const axis=new THREE.AxesHelper(0.12);axis.position.set(0.58,0,0.5);drone.add(axis);scene.add(drone);
const swarm=new THREE.Group();scene.add(swarm);swarm.visible=false;
const sun=new THREE.Mesh(new THREE.SphereGeometry(0.32,40,24),new THREE.MeshBasicMaterial({color:0xffc55a}));swarm.add(sun);
const orbiters=[];const tinyGeom=new THREE.BoxGeometry(0.045,0.008,0.045);const working=new THREE.MeshBasicMaterial({color:0x93c7ff});const failed=new THREE.MeshBasicMaterial({color:0x633e36});
for(let i=0;i<500;i++){const mesh=new THREE.Mesh(tinyGeom,working);swarm.add(mesh);orbiters.push(mesh);}
for(let j=0;j<5;j++){const points=[];for(let i=0;i<=150;i++){const a=i/150*Math.PI*2,r=0.85+j*0.2;points.push(new THREE.Vector3(Math.cos(a)*r,0,Math.sin(a)*r));}const ring=new THREE.Line(new THREE.BufferGeometry().setFromPoints(points),new THREE.LineBasicMaterial({color:0x334656}));ring.rotation.x=j*0.23;swarm.add(ring);}
function update(){scenario={...BASE,count:+$('count').value,au:+$('au').value,failure:+$('failure').value/100,delivery:+$('delivery').value/100};const r=calculate(scenario);$('count-out').value=scenario.count;$('au-out').value=scenario.au.toFixed(1)+' AU';$('failure-out').value=Math.round(scenario.failure*100)+'%';$('delivery-out').value=Math.round(scenario.delivery*100)+'%';$('net').textContent=r.net.toFixed(1)+' W';$('fleet').textContent=(r.fleet/1000).toFixed(2)+' kW';$('delivered').textContent=(r.delivered/1000).toFixed(2)+' kW';$('cost').textContent=r.capitalPerKwh===null?'No delivery':'$'+r.capitalPerKwh.toFixed(2);orbiters.forEach((mesh,i)=>{mesh.visible=i<scenario.count;mesh.material=i<Math.round(scenario.count*scenario.failure)?failed:working;});}
for(const id of ['count','au','failure','delivery'])$(id).addEventListener('input',update);
$('reset').onclick=()=>{for(const [id,value] of Object.entries({count:100,au:1,failure:0,delivery:0}))$(id).value=value;update();};
$('export').onclick=()=>{const data={kind:'illustrative solar power budget, not orbital simulation',assumptions:scenario,results:calculate(scenario),method:'Investment-case base sensitivity; independent annual failure and degradation at year boundaries; additional failed share is immediate. Capital per lifetime delivered kWh is not LCOE.',units:{power:'W',energy:'kWh',cost:'USD'},exclusions:['financing','operations','R&D','insurance','replacement','unallocated infrastructure'],limitations:'No thermal, deployment, collision, beam, receiver or flight validation. Receiver and disposal costs are assumed allocations, not engineered designs.'};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='sunseed-scenario.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
for(const id of ['single','swarm'])$(id).onclick=()=>{mode=id;drone.visible=id==='single';swarm.visible=id==='swarm';$('single').classList.toggle('active',id==='single');$('swarm').classList.toggle('active',id==='swarm');camera.position.set(...(id==='single'?[1.3,1.6,2.2]:[2.5,2.8,4]));controls.target.set(0,0,0);$('scene-title').textContent=id==='single'?'01 / COLLECTOR DRONE':'02 / SCHEMATIC SWARM';$('caption').textContent=id==='single'?'Nominal 1 m² active PV · packaging schematic · drag to inspect':'Heliocentric concept · sizes and spacing not to scale · rust = failed units';};
$('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?'Resume':'Pause';controls.autoRotate=!paused;};
new ResizeObserver(()=>{const {width,height}=$('canvas').getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/height;camera.updateProjectionMatrix();}).observe($('canvas'));
let phase=0,last=performance.now();function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,0.1);last=now;if(!paused)phase+=dt*0.14;orbiters.forEach((mesh,i)=>{if(!mesh.visible)return;const lane=i%5,r=0.85+lane*0.2,a=i*2.39996+phase/r**1.5;mesh.position.set(Math.cos(a)*r,-Math.sin(a)*r*Math.sin(lane*0.23),Math.sin(a)*r*Math.cos(lane*0.23));mesh.lookAt(0,0,0);});controls.update();renderer.render(scene,camera);}update();requestAnimationFrame(animate);
